language: cpp
compiler:
  - gcc

before_install:
  - if [ "$TRAVIS_MCSERVER_BUILD_TYPE" == "COVERAGE" ]; then sudo pip install cpp_coveralls; fi

  # g++4.8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # g++4.8
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

# Build MCServer
script: ./CIbuild.sh


env:
  global:
    - secure: "P0mU9OsE0Nbk4550oYovbbqNHCIjXkW6qOYhNkVZ8anhINuUvU2Vtb9ceLZPhhuEWxG/A+N3uzrsv5I65judOs/EsN01j9NqG8rAmd38cUmYCNLHE84yDu6upMby0hQt+2OuF1cb329IWedI8J93FxOBCenQwKsKedVwYq6rf9E="
  matrix:
    - TRAVIS_MCSERVER_BUILD_TYPE=RELEASE MCSERVER_PATH=./MCServer

# Notification Settings
notifications:
  email:
    on_success: change
    on_failure: always
    
addons:
  coverity_scan:
    project:
      name: "mc-server/MCServer"
      description: "Your project description here"
    notification_email: work.tycho@gmail.com
    build_command_prepend: cmake . -DBUILD_TOOLS=1 -DSELF_TEST=1
    build_command: make
    branch_pattern: coverity_scan
